"""add clinic_details table

Revision ID: 023053fd639c
Revises: 9c42a7d184ef
Create Date: 2026-07-28 11:55:51.366065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023053fd639c'
down_revision = '9c42a7d184ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_details',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('clinic_org_id', sa.Integer(), nullable=False),
    sa.Column('clinic_name', sa.String(length=255), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('doctor_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['intake_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clinic_details')
    # ### end Alembic commands ###
