"""initial schema

Revision ID: f12f53bbecb8
Revises: 
Create Date: 2026-06-25 12:59:22.627985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f12f53bbecb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intake_form_data', schema=None) as batch_op:
        batch_op.alter_column('personal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('medical',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('referral',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('consent',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('appointment',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('account',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_form_data_session_id'))
        batch_op.drop_constraint(batch_op.f('intake_form_data_session_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'intake_sessions', ['session_id'], ['id'])

    with op.batch_alter_table('intake_sessions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text("(now() + '48:00:00'::interval)"))
        batch_op.drop_index(batch_op.f('idx_sessions_expires_at'))
        batch_op.drop_index(batch_op.f('idx_sessions_status'))

    with op.batch_alter_table('intake_summaries', schema=None) as batch_op:
        batch_op.alter_column('generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('api_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('intake_summaries_session_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'intake_sessions', ['session_id'], ['id'])

    with op.batch_alter_table('intake_uploads', schema=None) as batch_op:
        batch_op.alter_column('uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_uploads_session_id'))
        batch_op.drop_constraint(batch_op.f('intake_uploads_session_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'intake_sessions', ['session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intake_uploads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('intake_uploads_session_id_fkey'), 'intake_sessions', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_uploads_session_id'), ['session_id'], unique=False)
        batch_op.alter_column('uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('intake_summaries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('intake_summaries_session_id_fkey'), 'intake_sessions', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('api_response',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('intake_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text("(now() + '48:00:00'::interval)"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('intake_form_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('intake_form_data_session_id_fkey'), 'intake_sessions', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_form_data_session_id'), ['session_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('account',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('appointment',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('consent',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('referral',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('medical',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('personal',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
